# This is a basic workflow to help you get started with Actions

name: Push Build to S3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run: echo Hello, world!

    # # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.

    # Install dependencies
    - name: Install Dependencies
      run: |
        echo Installing dependencies...
        npm ci

    # Lint
    - name: Linting
      run: |
        echo Linting...
        npm run lint

    # Build
    - name: Build
      run: |
        echo Building...
        npm run build

    # Install AWS CLI
    - name: Install AWS CLI
      run: |
        echo Deploying...
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
        && unzip awscliv2.zip \
        && sudo ./aws/install
        aws --version

    # Setup CLI
    - name: Setup AWS CLI
      run: |
        aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
        ${AWS_ACCESS_KEY_ID}
        ${AWS_SECRET_ACCESS_KEY}
        ${AWS_REGION}
        text
        EOF
