name: Lint, Test, and then Push Build to S3
on:
  push:
    branches: [ master ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci

    - name: Linting
      run: npm run lint

    - name: Build
      run: npm run build
    
    # Keep contents of dist folder for future jobs
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist

  deploy_to_s3:
    runs-on: ubuntu-latest
    needs: test_and_build # don't try to run this job until test_and_build is done

    steps:
    - uses: actions/checkout@v2

    # Download artifacts from previous job to artifacts/dist directory
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: artifacts/dist

    # Install AWS CLI (v 2.0.42)
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.42.zip" -o "awscliv2.zip" \
        && unzip awscliv2.zip \
        && sudo ./aws/install

    # Configure AWS CLI:
    #   - Read four required inputs until EOF marker.
    #   - Discard all output to be sure that we don't expose any secrets. This probably isn't
    #     necessary since GitHub masks secrets, but probably not a bad thing to do anyway.
    - name: Configure AWS CLI
      run: |
        aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        us-east-1
        text
        EOF

    - name: Push build to S3
      working-directory: artifacts
      run: |
        ls -R
        aws s3 sync ./dist s3://test-vue-project/test --acl public-read --cache-control no-cache --profile s3-sync-action
