# This is a basic workflow to help you get started with Actions

name: Push Build to S3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Install Dependencies
      run: npm ci

    # Lint
    - name: Linting
      run: npm run lint

    # Test
    - name: Build
      run: npm run build
    
    # Keep build for future jobs
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

    # Install AWS CLI
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.42.zip" -o "awscliv2.zip" \
        && unzip awscliv2.zip \
        && sudo ./aws/install

    # Configure AWS CLI
    # Notes:
    #   - Read four required inputs until EOF marker.
    #   - Discard all output to be sure that we don't expose any secrets.
    #     This probably insn't necessary since GitHub masks secrets, but not a bad thing to do anyway.
    - name: Configure AWS CLI
      run: |
        aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
        ${{ secrets.AWS_ACCESS_KEY_ID }}
        ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        us-east-1
        text
        EOF

    # Push Build to S3
    - name: Push build to S3
      run: aws s3 sync ./dist s3://test-vue-project/test --acl public-read --cache-control no-cache --profile s3-sync-action

        
